name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get NPM package version
      uses: martinbeentjes/npm-get-version-action@main
      id: package-version
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rubenfrcordeiro/better-localtunnel-server:${{ steps.package-version.outputs.current-version}}-SNAPSHOT
